#!/bin/bash

##########################
#                        #
#   The PBS directives   #
#                        #
##########################

#PBS -N overlap_MGMT
#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:59:59
#PBS -M caim@usc.edu
#PBS -m abe

##########################################
#                                        #
#   Output some useful job information.  #
#                                        #
##########################################

echo ------------------------------------------------------
echo -n 'Job is running on node '; cat $PBS_NODEFILE
echo ------------------------------------------------------
echo PBS: qsub is running on $PBS_O_HOST
echo PBS: originating queue is $PBS_O_QUEUE
echo PBS: executing queue is $PBS_QUEUE
echo PBS: working directory is $PBS_O_WORKDIR
echo PBS: execution mode is $PBS_ENVIRONMENT
echo PBS: job identifier is $PBS_JOBID
echo PBS: job name is $PBS_JOBNAME
echo PBS: node file is $PBS_NODEFILE
echo PBS: current home directory is $PBS_O_HOME
echo PBS: PATH = $PBS_O_PATH
echo ------------------------------------------------------

cd $PBS_O_WORKDIR
bedtools multiinter -i ../U87-MGMT-8_MC/U87-MGMT-8_combined_reads_REdig_sort_MC_U251-MGMT.bedgraph ../U87-MGMT-9_MC/U87-MGMT-9_combined_reads_REdig_sort_MC_U251-MGMT.bedgraph ../U87-MGMT-10_MC/U87-MGMT-10_combined_reads_REdig_sort_MC_U251-MGMT.bedgraph -header -names rep1 rep2 rep3 > MGMT.bed

awk 'NR==1 || $4 >2' MGMT.bed > MGMT_overlap.bed
awk -v OFS="\t" '{if($4==1) {gsub("chr","hs",$1); print "hs10","131264448","131266300",$1,$2,$3,"color=vvlyellow"} else if($4==2) {gsub("chr","hs",$1); print "hs10","131264448","131266300",$1,$2,$3,"color=dred"} else if($4==3) {gsub("chr","hs",$1); print "hs10","131264448","131266300",$1,$2,$3,"color=black"}}' MGMT.bed > MGMT_circos.txt 
#bedtools intersect -a ../U251-MGMT-2_MC/U251-MGMT-2_combined_reads_REdig_MC_U251-MGMT.bedgraph -b ../U251-MGMT-5_MC/U251-MGMT-5_combined_reads_REdig_MC_U251-MGMT.bedgraph > temp_MGMT_1.bed
#bedtools intersect -b ../U251-MGMT-2_MC/U251-MGMT-2_combined_reads_REdig_MC_U251-MGMT.bedgraph -a ../U251-MGMT-5_MC/U251-MGMT-5_combined_reads_REdig_MC_U251-MGMT.bedgraph > temp_MGMT_2.bed
#paste temp_MGMT_1.bed temp_MGMT_2.bed | awk -v OFS="\t" '{print $1,$2,$3,$4,$8}' > MGMT.bed

