#!/bin/bash

##########################
#                        #
#   The PBS directives   #
#                        #
##########################

#PBS -N U87-MGMT-10_flash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=23:59:59
#PBS -M caim@usc.edu
#PBS -m abe

##########################################
#                                        #
#   Output some useful job information.  #
#                                        #
##########################################

echo ------------------------------------------------------
echo -n 'Job is running on node '; cat $PBS_NODEFILE
echo ------------------------------------------------------
echo PBS: qsub is running on $PBS_O_HOST
echo PBS: originating queue is $PBS_O_QUEUE
echo PBS: executing queue is $PBS_QUEUE
echo PBS: working directory is $PBS_O_WORKDIR
echo PBS: execution mode is $PBS_ENVIRONMENT
echo PBS: job identifier is $PBS_JOBID
echo PBS: job name is $PBS_JOBNAME
echo PBS: node file is $PBS_NODEFILE
echo PBS: current home directory is $PBS_O_HOME
echo PBS: PATH = $PBS_O_PATH
echo ------------------------------------------------------

cd $PBS_O_WORKDIR
cp ../adaptor_trimming_Feb2017/U87-MGMT-10_1_val_1.fq /scratch/
cp ../adaptor_trimming_Feb2017/U87-MGMT-10_2_val_2.fq /scratch/
/auto/rcf-proj/wl/caim/usr/FLASH-1.2.11/flash --interleaved-output /scratch/U87-MGMT-10_1_val_1.fq /scratch/U87-MGMT-10_2_val_2.fq -d U87-MGMT-10 -M 140
cat U87-MGMT-10/out.notCombined.fastq U87-MGMT-10/out.extendedFrags.fastq > U87-MGMT-10_combined_reads.fastq
