#!/bin/bash

##########################
#                        #
#   The PBS directives   #
#                        #
##########################

#PBS -N trim_U87-MGMT-10
#PBS -l nodes=1:ppn=1
#PBS -l walltime=23:59:59
#PBS -M caim@usc.edu
#PBS -m abe

##########################################
#                                        #
#   Output some useful job information.  #
#                                        #
##########################################

echo ------------------------------------------------------
echo -n 'Job is running on node '; cat $PBS_NODEFILE
echo ------------------------------------------------------
echo PBS: qsub is running on $PBS_O_HOST
echo PBS: originating queue is $PBS_O_QUEUE
echo PBS: executing queue is $PBS_QUEUE
echo PBS: working directory is $PBS_O_WORKDIR
echo PBS: execution mode is $PBS_ENVIRONMENT
echo PBS: job identifier is $PBS_JOBID
echo PBS: job name is $PBS_JOBNAME
echo PBS: node file is $PBS_NODEFILE
echo PBS: current home directory is $PBS_O_HOME
echo PBS: PATH = $PBS_O_PATH
echo ------------------------------------------------------

cd $PBS_O_WORKDIR
gunzip -c /staging/wl/caim/project/raw_data/capture-C_Zhang_Feb2017/raw_data/U87-MGMT-10_HF3GJALXX_L7_1.fq.gz > U87-MGMT-10_1.fq
gunzip -c /staging/wl/caim/project/raw_data/capture-C_Zhang_Feb2017/raw_data/U87-MGMT-10_HF3GJALXX_L7_2.fq.gz > U87-MGMT-10_2.fq
trim_galore --paired U87-MGMT-10_1.fq U87-MGMT-10_2.fq

fastqc -o FASTQC_raw U87-MGMT-10_1.fq
fastqc -o FASTQC_trim U87-MGMT-10_1_val_1.fq

fastqc -o FASTQC_raw U87-MGMT-10_2.fq
fastqc -o FASTQC_trim U87-MGMT-10_2_val_2.fq
